version: '3.7'
services:

    db:
        container_name: {PROJECT_NAME}-db
        image: mysql:5.7
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: {PROJECT_NAME}_db
            MYSQL_USER: highfive
            MYSQL_PASSWORD: highfive
        volumes:
            - ./docker/data/mysql:/var/lib/mysql
        ports:
            - 3307:3306

    web:
        container_name: {PROJECT_NAME}-web
        build: ./docker
        links:
            - db:db
        depends_on:
            - db
        volumes:
            - ./:/var/www/html
        environment:
            - VIRTUAL_PORT=80
            - VIRTUAL_HOST={PROJECT_NAME}.test

networks:
    default:
        external:
            name: nginx-proxy
